site_name: cyklopper
baseline: Atelier vélo participatif Cyklopper
site_dir: public
theme:
  name: null
  custom_dir: 'theme'
nav:
  - Presentation: '01_presentation.md'
  - Information: '03_info.md'
  - Team: '02_team.md'

galery:
  - images/image-01.jpg
  - images/image-02.jpg
  - images/image-03.jpg

actu:
  - 'Atelier en mixité choisie avec les Déchainées - 28 avril'
  - 'brocante vélo - place saint-denis - mercredi 24 mai'
