site_name: cyklopper
baseline: Atelier vélo participatif Cyklopper
site_dir: public
theme:
  name: null
  custom_dir: 'theme'
nav:
  - Presentation: '01_presentation.md'
  - Information: '03_info.md'
  - Team: '02_team.md'
  - actu: 'actu.md'

galery:
  - images/image-01.jpg
  - images/image-02.jpg
  - images/image-03.jpg

actu:
  - 'Cosmik Bike Festival - 30/31 mai et 1<sup>er</sup>  juin - Zonneklopper.'
  - 'Brocante vélo - date à venir.'


plugins:
  - macros
