site_name: cyklopper
baseline: Atelier vélo participatif Cyklopper
site_dir: public
theme:
  name: null
  custom_dir: 'theme'
nav:
  - Presentation: '01_presentation.md'
  - Information: '03_info.md'
  - Team: '02_team.md'
  - actu: 'actu.md'

galery:
  - images/image-01.jpg
  - images/image-02.jpg
  - images/image-03.jpg

actu:
  - 'Cosmik Bike Festival · 4-5 juillet 2026 · 2<sup>è</sup> édition à ZonneKlopper.'
  - 'Brocante vélo · 23 mai (après-midi) · Albert, Forêt.'

plugins:
  - macros
